### PR TITLE
Added VMware

### PR DESCRIPTION
**Pull request by nbstrat**

### CODE REVIEW

**Comment by Merlin83b** [comment]
Might be best to create a "Virtualisation" category for this, and pull LXC and OpenVZ out of the Misc category and into it?

**Comment by nbstrat** [comment]
That sounds like a better long term approach. Will rework what I have using that approach.

**Comment by nbstrat** [comment]
vmware category changed to virtualization.  American English spelling was used (virtualization versus virtualisation)

**Comment by Merlin83b** [comment]
I don't think the "stopped tracking CNAME" should be in the PR - this repo definitely wants to use the CNAME

**Comment by nbstrat** [comment]
You are correct and this change was suppose to have only been to allow my forked branch to build without a warning messages from GitHub. It was not intended to be merged upstream.

Will get back to this as soon as time permits.

**Comment by nbstrat** [comment]
The changes for this PR are ready

**Pull request merged**
